manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: ncs
      url-base: https://github.com/nrfconnect

  defaults:
    remote: ncs
    
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: zephyr-v3.1.0
      import:
        name-allowlist:
          - cmsis
          - hal_nordic  
          - mbedtls
          - mcumgr
          - nrf_hw_models
          - segger
          - tinycrypt
          - zcbor

  self:
    path: app